### ISSUE TITLE
Can't publish my changes to my branch

### ISSUE THREAD

**Issue by lucianoh** [cop1000/js-koans#20]
Every time I try to create a pull request from my branch i get this error.
![image](https://cloud.githubusercontent.com/assets/22595449/19830630/cccb06d0-9dc9-11e6-885d-59431869b3af.png)
Any help would be greatly appreciated.

**Comment by marxspawn** [comment]
I was having the same problem with the desktop app. I used the app to clone the files to my drive then used Atom text editor to fix the errors. Try to create a [pull request] (https://github.com/cop1000/js-koans/pull/new/master) Then compare and merge from there and not the desktop app. Let me know if that helps any. Good luck

**Comment by lucianoh** [comment]
Thanks for the response @marxspawn! I tried doing this earlier but my github handle isn't even in the list of branches to choose from and I definitely made a branch in the desktop app.

**Comment by lucianoh** [comment]
@hectorsector my github handle doesn't show up in the list of branches. Do you know what the problem might be?

**Comment by hectorsector** [comment]
Apologies @lucianoh you should be able to, now. I will extend this project a bit for your class as GitHub was having a few hiccups last night and your class didn't have the proper access to push until today. If it works, feel free to close this issue, otherwise please let me know what you're seeing and we can take it from there.

**Comment by marxspawn** [comment]
Glad to see you got it :+1:
